### PR TITLE
Add method argument for longevity

### PR DESCRIPTION
**Pull request by patrickbarks**
Add `method` argument to `longevity` function to allow user to select which components to return (life expectancy, maximum longevity, or both), based on #13 .

Also includes edits to remove outstanding build errors in Dev branch (these are 'quick fixes' copied from recent edits to Master.)

Also fixes error in max longevity loop (variable `runs` had been inadvertently fixed at 1000), and includes edits to formatting and language of `longevity` documentation.

### CODE REVIEW

**Comment by patrickbarks** [comment]
@levisc8 Could you help me out with the continuous integration checks here, when you have some time? I'm not sure why they're failing or what needs to be changed. Could it be that they're not yet configured in the Devel branch?

**Comment by levisc8** [comment]
Yea, basically unless the .travis.yml file is also on the devel branch,
Travis thinks it's building something based on Ruby (its default setting).
I forgot to add it for Rage, but you can pretty much copy and paste from
the `master` branch to `devel`. See the .travis.yml in jonesor/Rcompadre
for how to modify it.

Not sure what's going on with Appveyor, I'll have to look at it later.
Based on the output log, I doubt it has anything to do with the code and
everything to do with my ineptitude in configuring it. In the meantime, if
your PR is passing on Travis but still failing on Appveyor for a non code
related reason, I wouldn't worry about it too much for now.

**Comment by patrickbarks** [comment]
Ok, thanks for the help! I've switched to working with a fork and removed my ability to push directly I think (for fear of my own ineptitude), so I'll leave the .travis.yml copying to you or someone else if that's ok (no rush on this though).

**Comment by levisc8** [comment]
I've added the necessary .yml's, but you might have to add another commit to trigger the checks again.

**Comment by patrickbarks** [comment]
I think the .yml files in the devel branch (for both travis and appveyor) may be missing code sections to install jonesor/Rcompadre. (Though there are still other warnings that may be causing the failure too). Thanks again for the help!

**Pull request merged**
