### PR TITLE
Updates to shape_surv

### PR DESCRIPTION
**Pull request by patrickbarks**
I have a student working on pace-shape stuff, and so have been looking into `shape_surv()`. I've made a few updates, that should be checked by @iainmstott 

1. Log-transform lx, as mentioned in #50. This also requires filtering `lx == 0` to avoid `log(lx) == -Inf`. (I think this update also flips the meaning of shape so that shape > 0 is now positive senescence, as currently scaled.)

2. Subset x and lx to `xmin <= x <= xmax` prior to shape calculation. (I think this is your intention with xmin/xmax, but correct me if not.)

3. Change 'zombie' check from `diff(lx) > 0` to `diff(lx) > 1e-7)`, to allow for floating point errors. (There are a couple dozen mats in COMPADRE that fail the stricter test even though SurvivalIssue <= 1).

4. Check `length(x) > 2` (after subsetting) rather than `xmax - xmin > 1`, to allow for age gradations < 1.

5. Updates for efficiency: switch from `makeLifeTable` to `mpm_to_lx` to avoid extraneous calculations, and cut all uses of `data.frame()`.

6. Merged `TrapezoidRule` (in kEntropy) and `.RageAUC` fns into `area_under_curve()` in utils.R. (They're all mathematically equivalent)

If you're generally on board with these, I can update `shape_rep` accordingly.

### CODE REVIEW

**Comment by patrickbarks** [comment]
Somewhat separate to the changes noted above, I've found that it's quite difficult to use `shape_surv` with MPMs, because the function fails whenever `qsdConverge < 3` or `lx[3] == 0` (error "xmax - xmin must be larger than 1"), which is the case for hundreds of matrices in COMPADRE. I'd favour removing the option to calculate shape directly from `matU`/`CompadreMat`, and instead encourage the user to first calculate lx (e.g. using `mpm_to_lx` or `makeLifeTable`), and then further subset/filter lx as appropriate (e.g. based on `qsdConverge`). Users may have to first calculate and subset based on `lx` and `qsdConverge` anyway, to avoid a ton of errors from `shape_surv`.

Relatedly, I think the current `matU` functionality is potentially dangerous because it hides the `min(lx)` and `length(lx)` used to calculate shape. For comparative purposes, I would be wary of a value of shape calculated from only 2 time steps, or where the minimum survivorship was >> 0 (or at least I'd want to know and account for those things). I think it could greatly simplify the code and docs if we cut the matU/MPM functionality, and focus solely on lx.

**Comment by patrickbarks** [comment]
Not related to the shape fns, but I added a potential fix for the `qsdConverge` issue mentioned in #52:

- if `matU` is not ergodic, first remove any stage classes that can never be reached from stage `startLife`; then calculate the stable distribution and time to QSD

For a set of 430 mean matrices in COMPADRE, there were only 25 non-ergodic `matU` that failed to converge to QSD under the previous function but do converge with this update (so the issue wasn't so big). Otherwise, the values returned are the same as before.

I also changed the `for` loop to a `while` loop, so e.g. if the QSD is reached at time 10, we don't need to run through the remaining 990 steps.

**Comment by iainmstott** [comment]
Agree with everything in your first message, and I've updated `shape_rep` to match, including removing the matU functionality in the two shape functions. 

I struggled with the `lx == 0` issue. I don't think we can just strip them out: if something has high mortality between `xmax - 1` and `xmax`, then that wouldn't be captured. I've put in truncation as an option, but also a warning (if there are any `lx == 0`) that it is also possible to replace the zero with a very small value (I don't know what exactly this should be). It's something we should probably have a better think about.

I wasn't a big fan of the removing life cycle stages to make the matrix ergodic... But I think I'm missing the context. How many non-ergodic ones were there in total? The solution for me depends on the nature of the life cycle. If there are missing values that don't need to be there (e.g. final stage has zero survival) then fine, but if it's just bad data and e.g. no age-2 individuals were recaptured in a species that lives to 25, then I'm more sceptical.I've gone for an option again, either to strip them or not at the user's discretion. 

But other than those two small problems, it's amazing. You've done loads! And it's looking sleek. I'm gonna be using it to do some very last-min analyses before a seminar on friday 😀 

You have a pull request from me relating to a branch PR51 I created to go through these changes (I didn't want to merge directly into my devel as I've got to use these things this week and wanted to be sure that I'd have working code, in case I screwed up!) Then one you're happy perhaps Owen can pull into the "official" repo.

I'll leave this open in case anyone wants to add anything...

**Comment by patrickbarks** [comment]
Sounds good! I think there's no solution to the `log(lx)` issue. If survivorship at time t is 0, the mortality hazard between t-1 and t is simply inestimable, so I think it's fine to strip these out. It's consistent with the approach of allowing partial lx trajectories, which I was skeptical of at first, but now am fully on board with. Artificially transforming lx(t) from 0 to 1e-7 just passes the buck to t+1.

Perhaps more importantly, the measure of shape could be highly sensitive to imputed values. E.g. as lx(t) approaches 0, the measure of shape will approach +0.5, regardless of the rest of the lx trajectory:
```
# trajectory with declining mortality hazard
hx <- seq(0.5, 0.1, -0.01)
lx <- hx_to_lx(hx)

shape_surv(lx)
>> [1] -0.109

shape_surv(c(lx, 1e-7))
>> [1] 0.029

shape_surv(c(lx, 1e-30))
>> [1] 0.380
```
So I'd favour removing the `trunc` option (and especially the advice to change values of 0 to some arbitrary small value) and simply stripping zeros as before, but with additional documentation explaining this. But I don't feel too strongly here.

Regarding the `qsdConverge` issue, for my 'working subset' of COMPADRE (excluding seasonal mats, annual spp., etc.), 1576/5352 `matU` are non-ergodic. If those rows are collapsed to a single mean matrix by species, 145/566 `matU` are non-ergodic. I'll respond in more detail to this in Issue #52.

**Comment by patrickbarks** [comment]
Added a few minor edits to the `shape_` fns, to remove an unnecessary check, fix a typo, add unit tests for `shape_rep`, and standardize the docs. It's definitely the case now that positive shape indicates positive senescence (perhaps this was the case in the code all along, but the documentation was opposite?).

I also:
- changed the `for` loop to a `while` loop in `longevity()`, for the sake of efficiency
- updated `qsdConverge` so that the population vector is standardized to sum to 1 at each iteration. This prevents occasional divide-by-zero errors when values in the population vector become very small (which used to result in an `NA` being returned), but otherwise doesn't change any results.

**Comment by jonesor** [comment]
Fantastic work!

**Pull request merged**
