### PR TITLE
Devel: shape functions

### PR DESCRIPTION
**Pull request by iainmstott**
Shape functions developed by Annette Baudisch and I for both survival and reproduction (shape_surv and shape_rep respectively). Should merge very cleanly, I might appreciate some testing of both the functions with lx and mx data; tested shape_rep with several data.frame examples and it seems to work as intended. Might be good to test it with a few matrices (functions use makeLifeTable so can take a matrix directly if need be). Other than that, enjoy :)

### CODE REVIEW

**Comment by patrickbarks** [comment]
Gave these a quick try. I like the `diff(lx) > 0` error message :) Few other thoughts:

- I noticed that the `shape_` fns use the convention that positive shape values indicate negative senescence and negative values indicate positive senescence, whereas all of Annette's shape paper's that I've read use the opposite convention. Perhaps consider rescaling?

- For `shape_surv`, I think the 0.5 baseline isn't quite right because a constant survival rate yields an exponential decline in lx rather than a linear decline. Perhaps you could just take the log of `lx` before calculating `lxStd`?

- Also, I wonder if there should be an optional argument to ensure that lx falls to 0 at/after `max(x)`. Otherwise these two `lx` trajectories will yield the same value of shape:
```
lx1 <- c(1, 0.9, 0.9, 0.9)
lx2 <- c(1, 0.1, 0.1, 0.1)
shape_surv(lx1) == shape_surv(lx2)
```
- In `shape_surv` the first group of checks (e.g. `if(is.null(xmin)) xmin <- min(x)`, ...) should be moved down farther, because `x` won't have been defined yet.

- The `shape_` fns don't work with matrices/`CompadreM` because `ifelse` only returns scalar values (assuming `test` returns a scalar `TRUE`/`FALSE`). Could update to `if {} else {}` here. In `.RageAUC` I think the `ifelse` should also be changed to avoid assignment within a function argument.

- In `shape_rep`, passing `list(matU, matF)` doesn't work because the fn only checks for a list with `x` and `mx`. Passing `CompadreM` doesn't work because of the `ifelse()` and also because there's no code to extract `matF` and pass it to `makeLifeTable`.

**Comment by iainmstott** [comment]
Thanks for the quick comments Patrick! In order:

* This is a misunderstanding between Annette and I. She said she'd change them in the paper, but I guess that happened for the version you saw. In the end the justification for the way it is in the package is that negative senescence is a 'positive' thing for the organism, and survival increases (hence the positive shape value), and vice versa for senescence. It does also make sense for negative senescence to have a negative value, but then conversely we don't talk about 'positive senescence'. It's a bit confusing.

* Correct, that's a mistake on my part. The lx curve should be logged!

* This is actually by design. If somebody wants to look at the shape of just part of the survival or reproduction curve then they can. I did have requirements for lx to start at 1 and end at 0 but I took them out. With reproduction it's a bit different: there cannot be a requirement for x or mx to start or end at any value, and Bx is by definition a cumulative curve starting at 0 and ending at 1 anyway. I also figured people might only have partial survival or reproduction data. In the end, if someone wants to look at a partial survival or reproduction curve then they can just standardise the numbers themselves anyway, so this just saves people (**cough** me) having to standardise the curves themselves and get the same outcome.

* Done, that was a mistake I fixed in `shape_rep` but not `shape_surv`.

* Done! Thanks

* lazy on my part! I've done a bunch of editing so it should work. I've tested all types of `rep` with my favourite tortoise matrix (_Gopherus agaszizii_ with medium fecundity), and seems to work fine. Probably worth testing with others though.

Pull request should now be updated

**Comment by patrickbarks** [comment]
Cool cool. Regarding the +/- convention I was only referring to Annette's _previous_ papers on the shape of senescence, where more positive values indicate stronger (positive) senescence:
- https://doi.org/10.1111/j.2041-210X.2010.00087.x
- https://doi.org/10.1111/1365-2745.12084
- https://doi.org/10.1371/journal.pone.0119163

**Comment by iainmstott** [comment]
Ohhhh, right. Thanks for clarifying. That hadn't actually occurred to me, and is a very good point. I've worked with mostly Keyfitz's delta before (without the transformation suggested). You know how I like consistency, we may have to change the sign from the code as it is. Honestly whichever way round it is, I think I'll be forever getting it confused.

**Comment by RobSalGo** [comment]
I suppose you mean entropy, no delta, @iainmstott ?

**Pull request merged**
