### PR TITLE
Minor edits to ms vignette

### PR DESCRIPTION
**Pull request by tdjames1**

### CODE REVIEW

**Comment by tdjames1** [comment]
I was going to add @PolCap @jjackson-eco as reviewers but they don't come up on the list - guys, these are just minor edits to the text but you might want to check you're happy with everything I've suggested.

**Comment by PolCap** [comment]
hi @tdjames1, I had a quick look and I am ok with all the changes. Thanks for having a look at this.

**Comment by tdjames1** [comment]
@jonesor I branched off my origin development branch by accident so there's a spurious commit in this PR, if it's a problem I can recreate the branch and submit a clean PR.

**Comment by jjackson-eco** [comment]
Sorry I'm a tad late to see this. All changes look good to me Tamora, thank you so much for this.

**Pull request merged**
